name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies for JAMS_2026
        working-directory: ./Tutorial/2026/JAMS_2026
        run: nci

      - name: Build JAMS_2026
        working-directory: ./Tutorial/2026/JAMS_2026
        run: nr build --base /${{github.event.repository.name}}/Tutorial/2026/JAMS_2026/

      - name: Install dependencies for zemi_guidance
        working-directory: ./Other/2026/zemi_guidance
        run: ni

      - name: Build zemi_guidance
        working-directory: ./Other/2026/zemi_guidance
        run: nr build --base /${{github.event.repository.name}}/Other/2026/zemi_guidance/

      - name: Install dependencies for well_being_lecture
        working-directory: ./Other/2026/well_being_lecture
        run: ni

      - name: Build well_being_lecture
        working-directory: ./Other/2026/well_being_lecture
        run: nr build --base /${{github.event.repository.name}}/Other/2026/well_being_lecture/

      - name: Install dependencies for otree_hosting
        working-directory: ./Other/2026/otree_hosting
        run: ni

      - name: Build otree_hosting
        working-directory: ./Other/2026/otree_hosting
        run: nr build --base /${{github.event.repository.name}}/Other/2026/otree_hosting/

      - name: Install dependencies for INAS
        working-directory: ./Conference/2026/INAS
        run: ni

      - name: Build INAS
        working-directory: ./Conference/2026/INAS
        run: nr build --base /${{github.event.repository.name}}/Conference/2026/INAS/

      - name: Create output directory structure
        run: |
          mkdir -p public/Tutorial/2026/JAMS_2026
          cp -r ./Tutorial/2026/JAMS_2026/dist/* public/Tutorial/2026/JAMS_2026/
          mkdir -p public/Other/2026/zemi_guidance
          cp -r ./Other/2026/zemi_guidance/dist/* public/Other/2026/zemi_guidance/
          mkdir -p public/Other/2026/well_being_lecture
          cp -r ./Other/2026/well_being_lecture/dist/* public/Other/2026/well_being_lecture/
          mkdir -p public/Other/2026/otree_hosting
          cp -r ./Other/2026/otree_hosting/dist/* public/Other/2026/otree_hosting/
          mkdir -p public/Conference/2026/INAS
          cp -r ./Conference/2026/INAS/dist/* public/Conference/2026/INAS/

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v5
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          timeout: 900000
          error_count: 20
          reporting_interval: 10000
